In [1]:
import numpy as np

In [2]:
# initialize a numpy array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# two dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#get dimensions of array
a.ndim

1

In [7]:
# get shape of array
# a.shape
b.shape

(2, 3)

In [9]:
# get size of array
a.size

3

Accessing/changing specific columns, rows and elements

In [10]:
# two dimensional array
a = np.array([[1, 2, 3,4,5,6,7,8,9,0], [11, 12, 13,14,15,16,17,18,19,20]])

In [11]:
# get specific element [r, c]
a[0, 0]


1

In [12]:
# get specific row
a[0, :]
# get first row and all the elements

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [13]:
# get specific column but only the 2 index elements
a[:, 2]

array([ 3, 13])

In [15]:
# get start index and end index and step size

a[0,1: 8: 2]
# gets the first row and all the elements from index 1 to 8 and step size 2

array([2, 4, 6, 8])

In [17]:
# change element at position [r, c] value
a[0, 0] = 100
a

array([[100,   2,   3,   4,   5,   6,   7,   8,   9,   0],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]])

In [18]:
# replace for an entire column
a[:, 2] = 100
a


array([[100,   2, 100,   4,   5,   6,   7,   8,   9,   0],
       [ 11,  12, 100,  14,  15,  16,  17,  18,  19,  20]])

# 3D elements


In [19]:
# 3d array
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [26]:
# get specific element [r, c, d]
a[0, 1, 2]

6

In [27]:
a[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])